settings:
  class_name: BuildConfiguration

environments:
  - Debug
  - Release

natrium_variables:
  BundleIdentifier:
    Debug: AppWork.TMDB-RIBs-iOS
    Release: AppWork.TMDB-RIBs-iOS

xcconfig:
  PRODUCT_BUNDLE_IDENTIFIER: "#{BundleIdentifier}"

variables:
  baseUrl:
    Debug: "#env(BASE_URL_LIVE)"
    Release: "#env(BASE_URL_LIVE)"
  baseUrlLocal:
    Debug: "#env(BASE_URL_LOCAL)"
    Release: "#env(BASE_URL_LOCAL)"
  baseImageW500Url:
    Debug: "#env(IMAGE_W500_BASE_URL)"
    Release: "#env(IMAGE_W500_BASE_URL)"
  token:
    Debug: "#env(TMDB_LIVE_TOKEN)"
    Release: "#env(TMDB_LIVE_TOKEN)"
  accountID:
    Debug: "#env(ACCOUNT_ID)"
    Release: "#env(ACCOUNT_ID)"

plists:
  "TMDB-RIBs-iOS/Info.plist":
    CFBundleDisplayName:
      Debug: TMDB-RIBs-iOS
      Release: TMDB-RIBs-iOS

    CFBundleIdentifier: "#{BundleIdentifier}"